stages:
  - restore
  - build
  - test

restore:
  stage: restore
  script:
    - $ErrorActionPreference = "Stop"
    - dotnet restore Routing.sln --source "https://api.nuget.org/v3/index.json"

build:
  stage: build
  script:
    - $ErrorActionPreference = "Stop"
    - dotnet build Routing.sln

tests:
  stage: test
  script:
    - $ErrorActionPreference = "Stop"
    - dotnet test Routing.sln --logger "trx;LogFileName=TestResults.trx"
    - '& "C:\Users\erlendd\.dotnet\tools\trx2junit.exe" *.Tests/TestResults/*.trx'
  artifacts:
    when: always
    reports:
      junit: '*.Tests/TestResults/*.xml'