stages:
  - restore
  - build
  - test

restore:
  stage: restore
  script:
    - $ErrorActionPreference = "Stop"
    - dotnet restore Routing.sln --source "https://api.nuget.org/v3/index.json"

build:
  stage: build
  script:
    - $ErrorActionPreference = "Stop"
    - dotnet build Routing.sln

tests:
  stage: test
  script:
    - $ErrorActionPreference = "SilentlyContinue"
    - dotnet test Routing.sln --logger "trx;LogFileName=TestResults.trx" --verbosity minimal; if ($LASTEXITCODE -ne 0) { $LASTEXITCODE = 0 }
    - C:\Users\erlendd\.dotnet\tools\trx2junit.exe Routing.Tests/TestResults/TestResults.trx
    - C:\Users\erlendd\.dotnet\tools\trx2junit.exe RoadNetworkRouting.Tests/TestResults/TestResults.trx
    - C:\Users\erlendd\.dotnet\tools\trx2junit.exe RoutingApi.Tests/TestResults/TestResults.trx
    - Get-ChildItem -Path './**/TestResults/*.trx' -Recurse | C:\Code\Gitlab\badge-tests.ps1 -label "routing-all"
    - Get-ChildItem -Path './Routing.Tests/TestResults/*.trx' -Recurse | C:\Code\Gitlab\badge-tests.ps1 -label "routing"
    - Get-ChildItem -Path './RoadNetworkRouting.Tests/TestResults/*.trx' -Recurse | C:\Code\Gitlab\badge-tests.ps1 -label "road-network-routing"
    - Get-ChildItem -Path './RoutingApi.Tests/TestResults/*.trx' -Recurse | C:\Code\Gitlab\badge-tests.ps1 -label "routing-api"
  artifacts:
    when: always
    paths:
      - tests.svg
    reports:
      junit: 
        - 'Routing.Tests/TestResults/TestResults.xml'
        - 'RoadNetworkRouting.Tests/TestResults/TestResults.xml'
        - 'RoutingApi.Tests/TestResults/TestResults.xml'